const randomNum = () => {
    return Math.floor(Math.random() * Math.floor(40))
}

const insults = {
    descriptorArray: ["pokey", "artless",
        "bawdy",
        "beslubbering",
        "bootless",
        "churlish",
        "cockered",
        "clouded",
        "craven",
        "currish",
        "dankish",
        "dissembling",
        "droning",
        "errant",
        "fawning",
        "fobbing",
        "froward",
        "frothy",
        "gleeking",
        "goatish",
        "gorbellied",
        "impertinent",
        "infectious",
        "jarring",
        "loggerheaded",
        "lumpish",
        "mammering",
        "mangled",
        "mewling",
        "paunchy",
        "pribbling",
        "puking",
        "puny",
        "qualing",
        "rank",
        "reeky",
        "roguish",
        "ruttish",
        "saucy",
        "spleeny",
        "spongy",
        "surly",
        "tottering",
        "unmuzzled",
        "vain",
        "venomed",
        "vallainous",
        "warped",
        "wayword",
        "weedy",
        "yeasty"],
    verbArray: ["little", "base-court",
        "bat-fowling",
        "beef-witted",
        "beetle-headed",
        "boil-brained",
        "clapper-clawed",
        "clay-brained",
        "common-kissing",
        "crook-pated",
        "dismal-dreaming",
        "dizzy-eyed",
        "doghearted",
        "dread-bolted",
        "earth-vexing",
        "elf-skinned",
        "fat-kidneyed",
        "fen-sucked",
        "flap-mouthed",
        "fly-bitten",
        "folly-fallen",
        "fool-born",
        "full-gorged",
        "guts-griping",
        "half-faced",
        "hasty-witted",
        "hedge-born",
        "hell-hated",
        "idle-headed",
        "ill-breeding",
        "ill-nurtured",
        "knotty-pated",
        "milk-livered",
        "motley-minded",
        "onion-eyed",
        "plume-plucked",
        "pottle-deep",
        "pox-marked",
        "reeling-ripe",
        "rough-hewn",
        "rude-growing",
        "rump-fed",
        "shard-borne",
        "sheep-biting",
        "spur-galled",
        "swag-bellied",
        "tardy-gaited",
        "tickle-brained",
        "toad-spotted",
        "unchin-snouted",
        "weather-bitten"],
    nounArray: ["flab-biscuit", "clotpole",
        "coxcomb",
        "codpiece",
        "death-token",
        "dewberry",
        "flap-dragon",
        "flax-wench",
        "flirt-gill",
        "foot-licker",
        "fustilarian",
        "giglet",
        "gudgeon",
        "haggard",
        "harpy",
        "hedge-pig",
        "horn-beast",
        "hugger-mugger",
        "joithead",
        "lewster",
        "lout",
        "maggot-pie",
        "malt-worm",
        "mammet",
        "measle",
        "minnow",
        "miscreant",
        "moldwarp",
        "mumble-news",
        "nut-hook",
        "pigeon-egg",
        "pignut",
        "puttock",
        "pumpion",
        "ratsbane",
        "scut",
        "skainsmate",
        "strumpet",
        "varlot",
        "vassal",
        "whey-face",
        "wagtail"],
    randomInsultForUser(user) {
        const firstWord = this.descriptorArray[randomNum()];
        if(firstWord.split("")[0].includes('a', 'e', 'i', 'o', 'u')){
            return `${user.username} is an ${firstWord}, ${this.verbArray[randomNum()]}, ${this.nounArray[randomNum()]}.`
        } else {
            return `${user.username} is a ${firstWord}, ${this.verbArray[randomNum()]}, ${this.nounArray[randomNum()]}.`
        }
    },
    randomInsultForName(name) {
        const firstWord = this.descriptorArray[randomNum()];
        console.log(firstWord)
        if(firstWord.split("")[0].includes('a', 'e', 'i', 'o', 'u')){
            return `${name} is an ${firstWord}, ${this.verbArray[randomNum()]}, ${this.nounArray[randomNum()]}.`
        } else {
            return `${name} is a ${firstWord}, ${this.verbArray[randomNum()]}, ${this.nounArray[randomNum()]}.`
        }
    },
    randomInsultForMe() {
        return `You ${this.descriptorArray[randomNum()]}, ${this.verbArray[randomNum()]}, ${this.nounArray[randomNum()]}.`
    }
}

module.exports = insults;